### ISSUE TITLE
al confirmar vuelve al Index

### ISSUE THREAD

**Issue by Lbenza** [TodoPago/Plugin-opencart2#2]
Hola! al confirmar la operación en el checkout vuelve al index. 
Este es el log de error:

[2017-02-13T23:19:01+00:00] DEBUG [ControllerPaymentTodopago(index:27) | /home/mercad13/public_html/catalog/controller/payment/todopago.php] ADMIN (PHPv.5.6.29 - eCv.2.0.2.0 - Pv.1.8.0) order_info: {"order_id":"10704","invoice_no":"0","invoice_prefix":"OR20988","store_id":"0","store_name":"12Pulgadas.net","store_url":"http:\/\/12pulgadas.net\/","customer_id":"230","firstname":"Luciano","lastname":"B","email":"info@12pulgadas.net","telephone":"1111111","fax":"","custom_field":{"1":"7488888"},"payment_firstname":"Luciano","payment_lastname":"B","payment_company":"","payment_address_1":"Jose luis Borges 2005","payment_address_2":"","payment_postcode":"1431","payment_city":"Neuquen","payment_zone_id":"162","payment_zone":"Capital Federal","payment_zone_code":"C","payment_country_id":"10","payment_country":"Argentina","payment_iso_code_2":"AR","payment_iso_code_3":"ARG","payment_address_format":"","payment_custom_field":{"2":"20-8323232-23"},"payment_method":"<img src=\"catalog\/view\/theme\/default\/image\/todopago.jpg\" \/>","payment_code":"todopago","shipping_firstname":"Luciano","shipping_lastname":"B","shipping_company":"","shipping_address_1":"Jose luis Borges 2005","shipping_address_2":"","shipping_postcode":"1431","shipping_city":"Neuquen","shipping_zone_id":"162","shipping_zone":"Capital Federal","shipping_zone_code":"C","shipping_country_id":"10","shipping_country":"Argentina","shipping_iso_code_2":"AR","shipping_iso_code_3":"ARG","shipping_address_format":"","shipping_custom_field":{"2":"20-8323232-23"},"shipping_method":"Env\u00edo Est\u00e1ndar por OCA a Sucursal","shipping_code":"ocaaspro.ocaaspro_12","comment":"","total":"1301.0000","order_status_id":"0","order_status":null,"affiliate_id":"0","commission":"0.0000","language_id":"2","language_code":"es","language_directory":"spanish","currency_id":"2","currency_code":"ARS","currency_value":"1.00000000","ip":"186.19.136.43","forwarded_ip":"","user_agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/56.0.2924.87 Safari\/537.36","accept_language":"es-419,es;q=0.8","date_modified":"2017-02-13 18:19:01","date_added":"2017-02-13 18:19:01"}
2017-02-13 23:19:03 - PHP Notice:  Undefined index: order_id in /home/mercad13/public_html/catalog/controller/payment/todopago.php on line 63
[2017-02-13T23:19:03+00:00] DEBUG [ControllerPaymentTodopago(first_step_todopago:64) | /home/mercad13/public_html/catalog/controller/payment/todopago.php] ADMIN (PHPv.5.6.29 - eCv.2.0.2.0 - Pv.1.8.0) order_id, entrda fstST: 
[2017-02-13T23:19:03+00:00] DEBUG [ControllerPaymentTodopago(setLoggerForPayment:329) | /home/mercad13/public_html/catalog/controller/payment/todopago.php] ADMIN (PHPv.5.6.29 - eCv.2.0.2.0 - Pv.1.8.0) order_info: false
[2017-02-13T23:19:03+00:00] WARN  [loggerFactory(createLogger:27) | /home/mercad13/public_html/admin/resources/todopago/Logger/loggerFactory.php] ADMIN (PHPv.5.6.29 - eCv.2.0.2.0 - Pv.1.8.0) Ha ocurrido un error creando el logger
exception 'Exception' with message 'Logger Configuracion incompleta' in /home/mercad13/public_html/admin/resources/todopago/Logger/logger.php:102
Stack trace:
#0 /home/mercad13/public_html/admin/resources/todopago/Logger/loggerFactory.php(23): TodoPagoLogger->getLogger(true)
#1 /home/mercad13/public_html/catalog/controller/payment/todopago.php(331): loggerFactory::createLogger(true, 'prod', NULL, NULL)
#2 /home/mercad13/public_html/catalog/controller/payment/todopago.php(93): ControllerPaymentTodopago->setLoggerForPayment(NULL)
#3 /home/mercad13/public_html/catalog/controller/payment/todopago.php(66): ControllerPaymentTodopago->prepareOrder()
#4 [internal function]: ControllerPaymentTodopago->first_step_todopago(Array)
#5 /home/mercad13/public_html/vqmod/vqcache/vq2-system_modification_system_engine_action.php(65): call_user_func(Array, Array)
#6 /home/mercad13/public_html/vqmod/vqcache/vq2-system_engine_front.php(86): Action->execute(Object(Registry))
#7 /home/mercad13/public_html/vqmod/vqcache/vq2-system_engine_front.php(60): Front->execute(Object(Action))
#8 /home/mercad13/public_html/index.php(259): Front->dispatch(Object(Action), Object(Action))
#9 {main}
2017-02-13 23:19:03 - PHP Notice:  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1<br />Error No: 1064<br />SELECT * FROM oc_todopago_transaccion WHERE id_orden =  in /home/mercad13/public_html/system/library/db/mysqli.php on line 41
2017-02-13 23:19:03 - PHP Notice:  Trying to get property of non-object in /home/mercad13/public_html/catalog/model/todopago/transaccion.php on line 12
2017-02-13 23:19:03 - PHP Notice:  Error: Column count doesn't match value count at row 1<br />Error No: 1136<br />INSERT INTO oc_todopago_transaccion (id_orden) VALUES () in /home/mercad13/public_html/system/library/db/mysqli.php on line 41
2017-02-13 23:19:03 - PHP Notice:  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1<br />Error No: 1064<br />SELECT * FROM oc_todopago_transaccion WHERE id_orden =  in /home/mercad13/public_html/system/library/db/mysqli.php on line 41
2017-02-13 23:19:03 - PHP Notice:  Trying to get property of non-object in /home/mercad13/public_html/catalog/model/todopago/transaccion.php on line 12
[2017-02-13T23:19:03+00:00] WARN  [ControllerPaymentTodopago(first_step_todopago:87) | /home/mercad13/public_html/catalog/controller/payment/todopago.php] ADMIN (PHPv.5.6.29 - eCv.2.0.2.0 - Pv.1.8.0) Fallo al iniciar el first step, Ya se encuentra registrado un first step exitoso en la tabla todopago_transaccion

**Comment by guillermoluced** [comment]
Este bug se resolvió, por favor probar la ultima versión del plugin.

**Comment by Lbenza** [comment]
Hola! instale el nuevo plug y el sitio me vuelve al index.

**Comment by Lbenza** [comment]
AYUDA!!

2017-09-27 10:27 GMT-03:00 Luciano Benzadon <lbenza@gmail.com>:
